/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EvernoteDecryptorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/constants/crypto.ts
var RESERVED_VALUE = "ENC0";
var SALT_LENGTH = 16;
var SALT_HMAC_LENGTH = 16;
var IV_LENGTH = 16;
var BODY_HMAC_LENGTH = 32;
var PBKDF2_ITERATIONS = 5e4;
var KEY_LENGTH = 16;
var HASH = "SHA-256";

// src/constants/plugin.ts
var PLUGIN_NAME = "Evernote Decryptor";
var FORMAT_PREFIX = "evernote_secret ";
var BUTTON_TEXT = "Evernote Secret";
var BUTTON_CLASS = "evernote-secret-button";
var ID_PREFIX = "evernote-dectyptor-";
var PLACEHOLDER_PREFIX = "EVERNOTE_DECRYPTOR_PLACEHOLDER";
var CMD_DECRYPT = "Decrypt Evernote encrypted data";
var CMD_DECRYPT_REPLACE = "Decrypt Evernote encrypted data and replace";
var CMD_ENCRYPT = "Encrypt data as Evernote secret";
var CMD_FORMAT = "Format Evernote secret";
var CMD_FORMAT_NOTE = "Format all Evernote secrets in the note";

// src/settings/SettingsTab.ts
var import_obsidian = require("obsidian");
var SettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: `${PLUGIN_NAME} Settings` });
    new import_obsidian.Setting(containerEl).setName("Show Editor Menu").setDesc("Show commands in the editor context menu").addToggle((toggle) => toggle.setValue(this.plugin.settings.showEditorMenu).onChange(async (value) => {
      this.plugin.settings.showEditorMenu = value;
      await this.plugin.saveSettings();
      this.plugin.updateContextMenu();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Mobile Buttons").setDesc("Show encryption/decryption buttons in the mobile toolbar").addToggle((toggle) => toggle.setValue(this.plugin.settings.showMobileButtons).onChange(async (value) => {
      this.plugin.settings.showMobileButtons = value;
      await this.plugin.saveSettings();
      this.plugin.unload();
      this.plugin.load();
    }));
  }
};

// src/utils/editorUtils.ts
var import_obsidian5 = require("obsidian");
var import_view = require("@codemirror/view");
var import_language = require("@codemirror/language");
var import_state = require("@codemirror/state");

// src/utils/cryptoUtils.ts
var import_obsidian3 = require("obsidian");

// src/modals/PasswordModal.ts
var import_obsidian2 = require("obsidian");
var PasswordModal = class extends import_obsidian2.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter Evernote encryption password." });
    this.createPasswordField(contentEl);
    this.createSubmitButton(contentEl);
  }
  onClose() {
    this.contentEl.empty();
  }
  createPasswordField(contentEl) {
    new import_obsidian2.Setting(contentEl).setName("Password").addText((text) => {
      this.passwordField = text.inputEl;
      this.passwordField.type = "password";
      this.passwordField.addEventListener("keypress", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          this.onPasswordSubmit();
        }
      });
    });
  }
  createSubmitButton(contentEl) {
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("Submit").setCta().onClick(() => {
      this.onPasswordSubmit();
    }));
  }
  onPasswordSubmit() {
    this.onSubmit(this.passwordField.value);
    this.close();
  }
};
function openPasswordModal(app) {
  return new Promise((resolve) => {
    new PasswordModal(app, resolve).open();
  });
}

// src/utils/cryptoUtils.ts
function reservedPart(reserved, encoded) {
  const n_bits = reserved.length * 8;
  const n_sixes = Math.floor(n_bits / 6);
  return encoded.slice(0, n_sixes);
}
function generateRandomBytes(length) {
  const array = new Uint8Array(length);
  crypto.getRandomValues(array);
  return array;
}
async function deriveBits(password, salt, iterations, bitsLength) {
  const enc = new TextEncoder();
  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    enc.encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveBits"]
  );
  return crypto.subtle.deriveBits(
    {
      name: "PBKDF2",
      salt,
      iterations,
      hash: HASH
    },
    keyMaterial,
    bitsLength
  );
}
async function pbkdf2Sync(password, salt, iterations, keylen) {
  const derivedBits = await deriveBits(password, salt, iterations, keylen * 8);
  return crypto.subtle.importKey(
    "raw",
    derivedBits,
    { name: "HMAC", hash: HASH },
    true,
    ["sign"]
  );
}
async function deriveKey(password, salt, keyLength, usage) {
  const enc = new TextEncoder();
  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    enc.encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveKey", "deriveBits"]
  );
  return crypto.subtle.deriveKey(
    {
      name: "PBKDF2",
      salt,
      iterations: PBKDF2_ITERATIONS,
      hash: HASH
    },
    keyMaterial,
    { name: "AES-CBC", length: keyLength * 8 },
    true,
    usage
  );
}
async function createHmac(key, data) {
  const importedKey = await crypto.subtle.importKey(
    "raw",
    await crypto.subtle.exportKey("raw", key),
    { name: "HMAC", hash: HASH },
    true,
    ["sign"]
  );
  return crypto.subtle.sign("HMAC", importedKey, data);
}
function concatenateArrays(...arrays) {
  const totalLength = arrays.reduce((sum, arr) => sum + arr.length, 0);
  const result = new Uint8Array(totalLength);
  let offset = 0;
  for (const arr of arrays) {
    result.set(arr, offset);
    offset += arr.length;
  }
  return result;
}
async function encrypt(text, password) {
  const reserved = new TextEncoder().encode(RESERVED_VALUE);
  const salt = generateRandomBytes(SALT_LENGTH);
  const saltHmac = generateRandomBytes(SALT_HMAC_LENGTH);
  const iv = generateRandomBytes(IV_LENGTH);
  const key = await deriveKey(password, salt, KEY_LENGTH, ["encrypt"]);
  const keyHmac = await pbkdf2Sync(password, saltHmac, PBKDF2_ITERATIONS, KEY_LENGTH);
  const enc = new TextEncoder();
  const plaintext = enc.encode(text);
  const ciphertext = await crypto.subtle.encrypt({ name: "AES-CBC", iv }, key, plaintext);
  const body = concatenateArrays(reserved, salt, saltHmac, iv, new Uint8Array(ciphertext));
  const bodyHmac = new Uint8Array(await createHmac(keyHmac, body));
  const finalData = concatenateArrays(body, bodyHmac);
  return btoa(String.fromCharCode(...finalData));
}
async function decrypt(text, password) {
  const binaryText = Uint8Array.from(atob(text), (c) => c.charCodeAt(0));
  let offset = RESERVED_VALUE.length;
  const { data: salt, newOffset: offsetAfterSalt } = extractDataSection(binaryText, offset, SALT_LENGTH);
  offset = offsetAfterSalt;
  const { data: saltHmac, newOffset: offsetAfterSaltHmac } = extractDataSection(binaryText, offset, SALT_HMAC_LENGTH);
  offset = offsetAfterSaltHmac;
  const { data: iv, newOffset: offsetAfterIv } = extractDataSection(binaryText, offset, IV_LENGTH);
  offset = offsetAfterIv;
  const ciphertext = binaryText.slice(offset, -BODY_HMAC_LENGTH);
  const body = binaryText.slice(0, -BODY_HMAC_LENGTH);
  const bodyHmac = binaryText.slice(-BODY_HMAC_LENGTH);
  const keyHmac = await pbkdf2Sync(password, saltHmac, PBKDF2_ITERATIONS, KEY_LENGTH);
  const testHmac = await createHmac(keyHmac, body);
  if (!compareDigests(new Uint8Array(testHmac), new Uint8Array(bodyHmac))) {
    throw new Error("HMAC verification failed");
  }
  const key = await deriveKey(password, salt, KEY_LENGTH, ["decrypt"]);
  const decrypted = await crypto.subtle.decrypt({ name: "AES-CBC", iv }, key, ciphertext);
  return new TextDecoder().decode(decrypted).replace(/<div>/g, "").replace(/<\/div>/g, "");
}
function extractDataSection(binaryData, startOffset, length) {
  return {
    data: binaryData.slice(startOffset, startOffset + length),
    newOffset: startOffset + length
  };
}
function timingSafeEqual(a, b) {
  let result = 0;
  for (let i = 0; i < a.length; i++) {
    result |= a[i] ^ b[i];
  }
  return result === 0;
}
function compareDigests(digest1, digest2) {
  return digest1.length === digest2.length && timingSafeEqual(digest1, digest2);
}
async function encryptWrapper(app, decryptedText) {
  const password = await openPasswordModal(app);
  if (password.trim() === "") {
    new import_obsidian3.Notice("\u26A0\uFE0F	Please enter a password.", 1e4);
    return null;
  }
  try {
    return await encrypt(decryptedText, password);
  } catch (error) {
    new import_obsidian3.Notice("\u274C Failed to encrypt.", 1e4);
    new import_obsidian3.Notice(error.message, 1e4);
    return null;
  }
}
async function decryptWrapper(app, encryptedText) {
  const password = await openPasswordModal(app);
  if (password.trim() === "") {
    new import_obsidian3.Notice("\u26A0\uFE0F	Please enter a password.", 1e4);
    return null;
  }
  try {
    return await decrypt(encryptedText, password);
  } catch (error) {
    new import_obsidian3.Notice("\u274C Failed to decrypt.", 1e4);
    new import_obsidian3.Notice(error.message, 1e4);
    return null;
  }
}

// src/modals/DecryptedTextModal.ts
var import_obsidian4 = require("obsidian");
var DecryptedTextModal = class extends import_obsidian4.Modal {
  constructor(app, decryptedText) {
    super(app);
    this.decryptedText = decryptedText;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Decrypted Text" });
    this.createTextArea(contentEl);
    this.createCopyButton(contentEl);
  }
  onClose() {
    this.contentEl.empty();
  }
  createTextArea(contentEl) {
    const textArea = contentEl.createEl("textarea");
    textArea.value = this.decryptedText;
    textArea.style.width = "100%";
    textArea.style.height = "auto";
    textArea.style.overflow = "hidden";
    textArea.readOnly = true;
  }
  createCopyButton(contentEl) {
    new import_obsidian4.Setting(contentEl).addButton((btn) => btn.setButtonText("Copy to Clipboard & Close").setCta().onClick(() => {
      navigator.clipboard.writeText(this.decryptedText);
      this.close();
      new import_obsidian4.Notice("Copied to clipboard");
    }));
  }
};

// src/utils/editorUtils.ts
async function showDecryptedText(app, encryptedText) {
  const decryptedText = await decryptWrapper(app, encryptedText);
  if (decryptedText !== null) {
    new DecryptedTextModal(app, decryptedText).open();
  }
}
function makeSecretButton(app, encryptedText, buttonText, buttonClass) {
  const button = document.createElement("button");
  button.textContent = buttonText;
  button.classList.add(buttonClass);
  button.onclick = (event) => {
    event.preventDefault();
    showDecryptedText(app, encryptedText);
  };
  return button;
}
var SecretButtonWidget = class extends import_view.WidgetType {
  constructor(app, encryptedText, buttonText, buttonClass) {
    super();
    this.app = app;
    this.encryptedText = encryptedText;
    this.buttonText = buttonText;
    this.buttonClass = buttonClass;
  }
  toDOM(_) {
    return makeSecretButton(this.app, this.encryptedText, this.buttonText, this.buttonClass);
  }
};
var makeViewPlugin = (app, prefix, buttonText, buttonClass) => import_view.ViewPlugin.fromClass(class {
  constructor(view) {
    this.decorations = this.createDecorations(view);
  }
  update(update) {
    if (!update.state.field(import_obsidian5.editorLivePreviewField)) {
      this.decorations = import_view.Decoration.none;
      return;
    }
    if (update.docChanged || update.viewportChanged || update.selectionSet) {
      this.decorations = this.createDecorations(update.view);
    }
  }
  createDecorations(view) {
    if (!view.state.field(import_obsidian5.editorLivePreviewField)) return import_view.Decoration.none;
    const builder = new import_state.RangeSetBuilder();
    const selection = view.state.selection;
    for (const { from, to } of view.visibleRanges) {
      (0, import_language.syntaxTree)(view.state).iterate({
        from,
        to,
        enter(node) {
          if (node.type.name.startsWith("inline-code")) {
            const value = view.state.doc.sliceString(node.from, node.to);
            if (value.startsWith(prefix)) {
              if (!selection.ranges.some((range) => range.from <= node.to + 1 && range.to >= node.from - 1)) {
                const encryptedText = value.slice(prefix.length);
                builder.add(
                  node.from,
                  node.to,
                  import_view.Decoration.replace({
                    widget: new SecretButtonWidget(app, encryptedText, buttonText, buttonClass)
                  })
                );
              }
            }
          }
        }
      });
    }
    return builder.finish();
  }
}, {
  decorations: (v) => v.decorations
});

// src/main.ts
var DEFAULT_SETTINGS = {
  showEditorMenu: true,
  showMobileButtons: true
};
var EvernoteDecryptorPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.commands = [];
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SettingTab(this.app, this));
    this.encryptedRegexp = new RegExp(`(?<=^| )${reservedPart(RESERVED_VALUE, btoa(RESERVED_VALUE))}[^ 
\`*_~]*`, "gm");
    this.codeBlockRegexp = /```[\s\S]+?```|^ {4,}(?![ *\-+]).*$|`[^\n`]+?`|\*\*[^\n*]+?\*\*|__[^\n_]+?__|~~[^\n~]+?~~|\*[^\n*]+?\*|_[^\n_]+?_/gm;
    if (import_obsidian6.Platform.isMobile && this.settings.showMobileButtons) {
      this.addMobileUI();
    }
    this.commands = [
      { id: "decrypt", name: CMD_DECRYPT, callback: (editor) => this.editorDecrypt(editor) },
      { id: "decrypt-replace", name: CMD_DECRYPT_REPLACE, callback: (editor) => this.decryptReplace(editor) },
      { id: "encrypt", name: CMD_ENCRYPT, callback: (editor) => this.makeSecret(editor) },
      { id: "format", name: CMD_FORMAT, callback: (editor) => this.formatSecret(editor) },
      { id: "format-note", name: CMD_FORMAT_NOTE, callback: (editor) => this.formatNoteSecrets(editor) }
    ];
    this.commands.forEach((command) => {
      this.addCommand({
        id: `${ID_PREFIX}${command.id}`,
        name: command.name,
        editorCallback: command.callback
      });
    });
    this.registerMarkdownPostProcessor((el, _) => {
      const codeBlocks = el.querySelectorAll("code");
      codeBlocks.forEach((codeBlock) => {
        if (codeBlock.parentElement === null) return;
        if (codeBlock.textContent === null) return;
        if (codeBlock.textContent.startsWith(FORMAT_PREFIX)) {
          const encryptedText = codeBlock.textContent.slice(FORMAT_PREFIX.length);
          codeBlock.style.display = "none";
          const button = makeSecretButton(this.app, encryptedText, BUTTON_TEXT, BUTTON_CLASS);
          codeBlock.parentElement.insertBefore(button, codeBlock);
        }
      });
    });
    this.registerEditorExtension(makeViewPlugin(this.app, FORMAT_PREFIX, BUTTON_TEXT, BUTTON_CLASS));
    this.updateContextMenu();
    console.log(`${PLUGIN_NAME} loaded`);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updateContextMenu() {
    if (this.contextMenuListener) {
      this.app.workspace.off("editor-menu", this.contextMenuListener);
    }
    this.contextMenuListener = (menu, editor) => {
      if (this.settings.showEditorMenu) {
        this.commands.forEach((command) => {
          menu.addItem((item) => {
            item.setTitle(command.name).onClick(() => command.callback(editor));
          });
        });
      }
    };
    this.registerEvent(this.app.workspace.on("editor-menu", this.contextMenuListener));
  }
  editorDecrypt(editor) {
    const selectedText = editor.getSelection();
    showDecryptedText(this.app, selectedText);
  }
  async decryptReplace(editor) {
    let selectedText = editor.getSelection().trim().replace(/^`+|`+$/g, "");
    if (selectedText.startsWith(FORMAT_PREFIX)) {
      selectedText = selectedText.slice(FORMAT_PREFIX.length);
    }
    const decryptedText = await decryptWrapper(this.app, selectedText);
    if (decryptedText !== null) {
      editor.replaceSelection(decryptedText);
    }
  }
  async makeSecret(editor) {
    const selectedText = editor.getSelection();
    const encryptedText = await encryptWrapper(this.app, selectedText);
    if (encryptedText !== null) {
      const formattedText = `\`${FORMAT_PREFIX}${encryptedText}\``;
      editor.replaceSelection(formattedText);
    }
  }
  formatSecret(editor) {
    const selectedText = editor.getSelection();
    const formattedText = `\`${FORMAT_PREFIX}${selectedText}\``;
    editor.replaceSelection(formattedText);
  }
  formatNoteSecrets(editor) {
    let doc = editor.getValue();
    const matches = [];
    doc = doc.replace(this.codeBlockRegexp, (match) => {
      const placeholder = `__${PLACEHOLDER_PREFIX}_${matches.length}__`;
      matches.push({ placeholder, content: match });
      return placeholder;
    });
    doc = doc.replace(this.encryptedRegexp, (match) => {
      return `\`${FORMAT_PREFIX}${match}\``;
    });
    matches.forEach(({ placeholder, content }) => {
      doc = doc.replace(placeholder, content);
    });
    editor.setValue(doc);
  }
  addMobileUI() {
    const mobileToolbar = this.addStatusBarItem();
    const encryptButton = mobileToolbar.createEl("button", {
      text: "\u{1F512}",
      cls: "mobile-encrypt-button"
    });
    const decryptButton = mobileToolbar.createEl("button", {
      text: "\u{1F513}",
      cls: "mobile-decrypt-button"
    });
    encryptButton.addEventListener("click", () => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
      if (activeView && activeView.editor) {
        this.makeSecret(activeView.editor);
      }
    });
    decryptButton.addEventListener("click", () => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
      if (activeView && activeView.editor) {
        this.editorDecrypt(activeView.editor);
      }
    });
  }
  onunload() {
    console.log(`${PLUGIN_NAME} unloaded`);
  }
};

/* nosourcemap */