# HubToday AI News Fetcher
# Fetches AI daily news and creates a daily note

param(
    [string]$Date = (Get-Date -Format "yyyy-MM-dd")
)

$WikiPath = "D:\GitHub\my-wiki\KB"
$DailyPath = "$WikiPath\01_Daily"
$LogFile = "$WikiPath\fetch.log"

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMsg = "$timestamp - $Message"
    if (Test-Path $LogFile) {
        Add-Content -Path $LogFile -Value $logMsg
    } else {
        Set-Content -Path $LogFile -Value $logMsg
    }
}

# Get date parts
$year = $Date.Substring(0, 4)
$month = $Date.Substring(5, 2)
$day = $Date.Substring(8, 2)
$displayDate = "$year/$month/$day"

# URL for AI news
$aiNewsUrl = "https://ai.hubtoday.app/$year-$month/$year-$month-$day/"

Write-Log "Fetching AI News from: $aiNewsUrl"

$textContent = ""

# Fetch AI news page
try {
    $response = Invoke-WebRequest -Uri $aiNewsUrl -TimeoutSec 30 -UseBasicParsing
    $htmlStr = $response.Content
    
    # Extract meta description using simple string operations
    $pattern = 'description content='
    $idx = $htmlStr.IndexOf($pattern)
    
    if ($idx -ge 0) {
        $start = $idx + $pattern.Length + 1
        $end = $htmlStr.IndexOf('"', $start)
        if ($end -gt $start) {
            $textContent = $htmlStr.Substring($start, $end - $start)
            # Clean up whitespace
            $textContent = $textContent -replace '\s+', ' '
            $textContent = $textContent.Trim()
            Write-Log "Extracted content: $($textContent.Length) chars"
        }
    } else {
        Write-Log "No meta description found"
    }
    
} catch {
    Write-Log "Error fetching AI news: $_"
}

# Prepare daily note content
$noteFileName = "$DailyPath\$Date.md"

# Build the AI section
$aiSection = "`n`n## AI News Daily ($displayDate)`n`n**Source**: $aiNewsUrl`n`n$textContent`n"

# Check if file already exists
if (Test-Path $noteFileName) {
    Write-Log "Note already exists: $noteFileName"
    
    # Read existing content
    $existingContent = Get-Content $noteFileName -Raw -Encoding UTF8
    
    # Check if AI section already exists
    if ($existingContent -notmatch '## AI News Daily') {
        Add-Content -Path $noteFileName -Value $aiSection -Encoding UTF8
        Write-Log "Appended AI news to existing note"
    } else {
        Write-Log "AI section already exists in note"
    }
} else {
    # Create new daily note using simple string concatenation
    $header = "---"
    $meta1 = "created: $Date"
    $meta2 = "tags: #daily #AInews"
    $meta3 = "source: $aiNewsUrl"
    $footer = "---"
    $title = "# $Date Daily"
    $completed = "## Today's Completed"
    $completedContent = "- "
    $reflections = "## Reflections"
    $reflectionsContent = ""
    $todo = "## Tomorrow Todo"
    $todoContent = "- [ ] "
    $inbox = "## Inbox"
    $inboxContent = ""
    $autoGen = "---`n*Auto-generated by AI Knowledge Base System*"
    
    $fullNoteContent = "$header`n$meta1`n$meta2`n$meta3`n$footer`n`n$title`n$aiSection`n$completed`n$completedContent`n`n$reflections`n$reflectionsContent`n`n$todo`n$todoContent`n`n$inbox`n$inboxContent`n`n$autoGen"
    
    Set-Content -Path $noteFileName -Value $fullNoteContent -Encoding UTF8
    Write-Log "Created new daily note: $noteFileName"
}

Write-Log "=== Fetch completed ==="
